name: Local
values:
  - key: base_url
    value: 'http://127.0.0.1:8000/api'
    enabled: true
    type: default

  - key: admin_username
    value: 'bellevue@admin.com'
    enabled: true
    type: default

  - key: admin_password
    value: 'admin123'
    enabled: true
    type: default

  - key: admin_token
    value: ''
    enabled: true
    type: default