// src/data/seatMapData.js
// Default seat layout data.
// TABLE_T1  — used by AlabangReserve (single-table client view)
// SEAT_MAP_DATA — used by Dashboard (full multi-wing admin view)

export const TABLE_T1 = {
  id: "T1",
  label: "Table 1",
  tableStatus: "available",
  capacity: 16,
  x: 140,
  y: 80,
  width: 80,
  height: 276,
  seats: [
    { id: "S15", num: 15, pos: "left",   status: "reserved",  x: -48, y: 0   },
    { id: "S13", num: 13, pos: "left",   status: "available", x: -48, y: 46  },
    { id: "S11", num: 11, pos: "left",   status: "available", x: -48, y: 92  },
    { id: "S9",  num: 9,  pos: "left",   status: "available", x: -48, y: 138 },
    { id: "S7",  num: 7,  pos: "left",   status: "available", x: -48, y: 184 },
    { id: "S5",  num: 5,  pos: "left",   status: "available", x: -48, y: 230 },
    { id: "S3",  num: 3,  pos: "left",   status: "available", x: -48, y: 276 },
    { id: "S16", num: 16, pos: "right",  status: "pending",   x: 88,  y: 0   },
    { id: "S14", num: 14, pos: "right",  status: "reserved",  x: 88,  y: 46  },
    { id: "S12", num: 12, pos: "right",  status: "available", x: 88,  y: 92  },
    { id: "S10", num: 10, pos: "right",  status: "available", x: 88,  y: 138 },
    { id: "S8",  num: 8,  pos: "right",  status: "available", x: 88,  y: 184 },
    { id: "S6",  num: 6,  pos: "right",  status: "available", x: 88,  y: 230 },
    { id: "S4",  num: 4,  pos: "right",  status: "available", x: 88,  y: 276 },
    { id: "S1",  num: 1,  pos: "bottom", status: "available", x: 0,   y: 324 },
    { id: "S2",  num: 2,  pos: "bottom", status: "pending",   x: 46,  y: 324 },
  ],
};

// Full seat map for all wings/rooms — used by the admin Dashboard
export const SEAT_MAP_DATA = {
  "Main Wing": {
    "Alabang Function Room": { ...TABLE_T1 },
    "Laguna Ballroom": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 8,
      x: 140,
      y: 80,
      width: 80,
      height: 184,
      seats: [
        { id: "L1", num: 1, pos: "left",  status: "available", x: -48, y: 0   },
        { id: "L2", num: 2, pos: "left",  status: "available", x: -48, y: 46  },
        { id: "L3", num: 3, pos: "left",  status: "available", x: -48, y: 92  },
        { id: "L4", num: 4, pos: "left",  status: "pending",   x: -48, y: 138 },
        { id: "L5", num: 5, pos: "right", status: "available", x: 88,  y: 0   },
        { id: "L6", num: 6, pos: "right", status: "reserved",  x: 88,  y: 46  },
        { id: "L7", num: 7, pos: "right", status: "available", x: 88,  y: 92  },
        { id: "L8", num: 8, pos: "right", status: "available", x: 88,  y: 138 },
      ],
    },
    "20/20 Function Room": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 8,
      x: 140,
      y: 80,
      width: 80,
      height: 184,
      seats: [
        { id: "F1", num: 1, pos: "left",  status: "available", x: -48, y: 0   },
        { id: "F2", num: 2, pos: "left",  status: "pending",   x: -48, y: 46  },
        { id: "F3", num: 3, pos: "left",  status: "available", x: -48, y: 92  },
        { id: "F4", num: 4, pos: "left",  status: "available", x: -48, y: 138 },
        { id: "F5", num: 5, pos: "right", status: "available", x: 88,  y: 0   },
        { id: "F6", num: 6, pos: "right", status: "available", x: 88,  y: 46  },
        { id: "F7", num: 7, pos: "right", status: "reserved",  x: 88,  y: 92  },
        { id: "F8", num: 8, pos: "right", status: "available", x: 88,  y: 138 },
      ],
    },
    "Business Center": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 6,
      x: 140,
      y: 80,
      width: 80,
      height: 138,
      seats: [
        { id: "B1", num: 1, pos: "left",  status: "available", x: -48, y: 0   },
        { id: "B2", num: 2, pos: "left",  status: "available", x: -48, y: 46  },
        { id: "B3", num: 3, pos: "left",  status: "available", x: -48, y: 92  },
        { id: "B4", num: 4, pos: "right", status: "reserved",  x: 88,  y: 0   },
        { id: "B5", num: 5, pos: "right", status: "available", x: 88,  y: 46  },
        { id: "B6", num: 6, pos: "right", status: "available", x: 88,  y: 92  },
      ],
    },
  },
  "Tower Wing": {
    "Tower Ballroom": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 8,
      x: 140,
      y: 80,
      width: 80,
      height: 184,
      seats: [
        { id: "TW1", num: 1, pos: "left",  status: "available", x: -48, y: 0   },
        { id: "TW2", num: 2, pos: "left",  status: "available", x: -48, y: 46  },
        { id: "TW3", num: 3, pos: "left",  status: "available", x: -48, y: 92  },
        { id: "TW4", num: 4, pos: "left",  status: "available", x: -48, y: 138 },
        { id: "TW5", num: 5, pos: "right", status: "available", x: 88,  y: 0   },
        { id: "TW6", num: 6, pos: "right", status: "available", x: 88,  y: 46  },
        { id: "TW7", num: 7, pos: "right", status: "available", x: 88,  y: 92  },
        { id: "TW8", num: 8, pos: "right", status: "available", x: 88,  y: 138 },
      ],
    },
    "Grand Ballroom": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 8,
      x: 140,
      y: 80,
      width: 80,
      height: 184,
      seats: [
        { id: "GB1", num: 1, pos: "left",  status: "available", x: -48, y: 0   },
        { id: "GB2", num: 2, pos: "left",  status: "available", x: -48, y: 46  },
        { id: "GB3", num: 3, pos: "left",  status: "available", x: -48, y: 92  },
        { id: "GB4", num: 4, pos: "left",  status: "available", x: -48, y: 138 },
        { id: "GB5", num: 5, pos: "right", status: "available", x: 88,  y: 0   },
        { id: "GB6", num: 6, pos: "right", status: "available", x: 88,  y: 46  },
        { id: "GB7", num: 7, pos: "right", status: "available", x: 88,  y: 92  },
        { id: "GB8", num: 8, pos: "right", status: "available", x: 88,  y: 138 },
      ],
    },
  },
  "Dining": {
    "Qsina": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 4,
      x: 140,
      y: 80,
      width: 80,
      height: 92,
      seats: [
        { id: "Q1", num: 1, pos: "left",  status: "available", x: -48, y: 0  },
        { id: "Q2", num: 2, pos: "left",  status: "available", x: -48, y: 46 },
        { id: "Q3", num: 3, pos: "right", status: "available", x: 88,  y: 0  },
        { id: "Q4", num: 4, pos: "right", status: "available", x: 88,  y: 46 },
      ],
    },
    "Hanakazu": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 4,
      x: 140,
      y: 80,
      width: 80,
      height: 92,
      seats: [
        { id: "H1", num: 1, pos: "left",  status: "available", x: -48, y: 0  },
        { id: "H2", num: 2, pos: "left",  status: "available", x: -48, y: 46 },
        { id: "H3", num: 3, pos: "right", status: "available", x: 88,  y: 0  },
        { id: "H4", num: 4, pos: "right", status: "available", x: 88,  y: 46 },
      ],
    },
    "Phoenix Court": {
      id: "T1",
      label: "Table 1",
      tableStatus: "available",
      capacity: 4,
      x: 140,
      y: 80,
      width: 80,
      height: 92,
      seats: [
        { id: "PC1", num: 1, pos: "left",  status: "available", x: -48, y: 0  },
        { id: "PC2", num: 2, pos: "left",  status: "available", x: -48, y: 46 },
        { id: "PC3", num: 3, pos: "right", status: "available", x: 88,  y: 0  },
        { id: "PC4", num: 4, pos: "right", status: "available", x: 88,  y: 46 },
      ],
    },
  },
};